dist: trusty
language: python
python:
    - "3.5"
addons:
    apt:
        packages:
            - texlive
            - texlive-latex-extra
install:
    - "deactivate"
    - "make setup PYTHON=/opt/python/3.5/bin/python"
    - "bin/pip install coveralls"
script: "make check && travis_wait 40 make test && make docs"
after_success: "bin/coveralls"
